name = "gitsocial"
main = "worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "gitsocial_db"
database_id = "89f91acf-d523-4c97-9151-b6bde6957450"

[assets]
directory = "./public"
